# Generated by Django 3.0.5 on 2020-09-19 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmdbBaseManagement', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Audit',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
